name: OS

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

jobs:

  macos:
    runs-on: macos-latest
    name: MacOS
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install Qt 6
      run: brew install qt@6

    - name: Configure build
      run: |
        cmake -DCI= --preset debug

    - name: Execute build
      run: |
        cmake --build --preset app-debug

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: app-macos
        path: |
          build/app

  windows:
    runs-on: windows-2022
    name: Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install Qt 6
      uses: jurplel/install-qt-action@v4
      with:
        version: "6.9.0"

    - name: Configure build
      run: |
        cmake -DCI= cmake --preset debug

    - name: Execute build
      run: |
        cmake --build --preset app-debug

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: app-windows
        path: |
          build/debug/app.exe

  linux:
    runs-on: ubuntu-22.04
    name: Linux
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build project using docker
      run: |
        docker buildx build . -f dist/linux.Dockerfile --progress=plain --output out

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: app-linux
        path: |
          out/app
