name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  linux:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build project using docker
        run: |
          docker buildx build . -f dist/linux.Dockerfile --progress=plain --output out
      - name: Rename executable
        run: |
          mv out/app out/app-linux
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/app-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-latest
    name: MacOS
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: install Qt 6
      run: brew install qt@6
    - name: Build project
      run: |
        cmake -B build
        cmake --build build -j 5
    - name: Rename executable
      run: |
        mv build/app build/app-macos
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/app-macos
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  windows:
    runs-on: windows-2022
    name: Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: install Qt 6
      uses: jurplel/install-qt-action@v4
      with:
        version: "6.9.0"
        cache: 'true'
    - name: Build project
      run: |
        cmake -S . -B build
        cmake --build build --config Debug
    - name: Rename executable
      run: |
        cp build/Debug/app.exe build/app.exe
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/app.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
